import Head from "next/head";
import ImageCarousel from "@/components/ImageCarousel";
import StorySlider from "@/components/StorySlider";
import { Container, Typography } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Carousel Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container sx={{ my: "50px" }} maxWidth="lg">
        <Typography variant="h4" sx={{ m: "20px" }}>
          Image Carousel
        </Typography>
        <StorySlider />
        <ImageCarousel title="Top in Art" />
      </Container>
    </>
  );
}
